// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtmtq4V6zhbDS7qJZH5Kz62z1uxsJ43LY',
    appId: '1:511904374346:web:dbdd8cb5aacf0d4b7510b3',
    messagingSenderId: '511904374346',
    projectId: 'flutter-entregadev',
    authDomain: 'flutter-entregadev.firebaseapp.com',
    storageBucket: 'flutter-entregadev.firebasestorage.app',
    measurementId: 'G-MK6CXSV99S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzavBkt7euoR78rkpw2EmBz_qHlcK9FxE',
    appId: '1:511904374346:android:23fe25c44ee3d3b77510b3',
    messagingSenderId: '511904374346',
    projectId: 'flutter-entregadev',
    storageBucket: 'flutter-entregadev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd79AnnJjQKcAhWaMVc95FQU-b4Ui3w1w',
    appId: '1:511904374346:ios:fa1c21e1058668a97510b3',
    messagingSenderId: '511904374346',
    projectId: 'flutter-entregadev',
    storageBucket: 'flutter-entregadev.firebasestorage.app',
    iosBundleId: 'com.example.entregaDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd79AnnJjQKcAhWaMVc95FQU-b4Ui3w1w',
    appId: '1:511904374346:ios:fa1c21e1058668a97510b3',
    messagingSenderId: '511904374346',
    projectId: 'flutter-entregadev',
    storageBucket: 'flutter-entregadev.firebasestorage.app',
    iosBundleId: 'com.example.entregaDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtmtq4V6zhbDS7qJZH5Kz62z1uxsJ43LY',
    appId: '1:511904374346:web:118f8509b275fd4a7510b3',
    messagingSenderId: '511904374346',
    projectId: 'flutter-entregadev',
    authDomain: 'flutter-entregadev.firebaseapp.com',
    storageBucket: 'flutter-entregadev.firebasestorage.app',
    measurementId: 'G-36Y568FQ3N',
  );
}
